import React, { useState, useEffect, useRef } from 'react';
import { 
  Sparkles, 
  Send, 
  X, 
  Maximize2, 
  Minimize2, 
  Trash2, 
  Copy, 
  Check, 
  Bot, 
  User as UserIcon, 
  TrendingUp,
  ShieldCheck,
  FileSpreadsheet,
  GraduationCap
} from 'lucide-react';
import { api } from '../../services/api';
import type { User, ChatMessage, ChatMessageTurn } from '../../types';

interface AIChatAssistantProps {
  user: User | null;
  isOpen: boolean;
  onClose: () => void;
  onOpen: () => void;
}

const STARTER_PROMPTS = [
  {
    title: "CPI vs WPI Methodologies",
    subtitle: "Basket composition, base years & MoSPI calculation formulas",
    prompt: "What is the key methodological difference between Consumer Price Index (CPI) and Wholesale Price Index (WPI) in India, including their base years and commodity weightages?",
    category: "Methodology",
    icon: TrendingUp,
    color: "from-blue-500/20 to-cyan-500/20 text-cyan-300 border-cyan-500/30"
  },
  {
    title: "Zero-Hallucination HITL",
    subtitle: "How human trainers audit AI-generated psychometric items",
    prompt: "How does the SmartSkill Human-in-the-Loop (HITL) review process ensure questions generated by Gemini maintain strict source grounding with zero hallucinations?",
    category: "HITL Quality",
    icon: ShieldCheck,
    color: "from-amber-500/20 to-orange-500/20 text-amber-300 border-amber-500/30"
  },
  {
    title: "OCR & Tabular Matrices",
    subtitle: "Preserving row-column relationships in complex PDF manuals",
    prompt: "How does the ingestion pipeline extract dense statistical matrices from MoSPI government publications without losing hierarchical context?",
    category: "Ingestion",
    icon: FileSpreadsheet,
    color: "from-indigo-500/20 to-purple-500/20 text-indigo-300 border-indigo-500/30"
  },
  {
    title: "iGOT Civil Service Remediation",
    subtitle: "Bridging statistical competency gaps with Karmayogi courses",
    prompt: "How does SmartSkill AI map individual officer competency diagnostic gaps to personalized course recommendations on iGOT Karmayogi?",
    category: "Capacity",
    icon: GraduationCap,
    color: "from-emerald-500/20 to-teal-500/20 text-emerald-300 border-emerald-500/30"
  }
];

export const AIChatAssistant: React.FC<AIChatAssistantProps> = ({
  user,
  isOpen,
  onClose,
  onOpen,
}) => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [activeModel, setActiveModel] = useState<string>('gemini-3.8-flash');
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  // Initialize with personalized executive greeting
  useEffect(() => {
    if (messages.length === 0) {
      const greeting = user
        ? `Namaste, **${user.full_name}** (${user.role === 'admin' ? 'Admin Trainer' : 'Statistical Officer'}). I am your **MoSPI SmartSkill AI Assistant**, powered by **Google Gemini**.\n\nI am grounded in official MoSPI publications and the iGOT Karmayogi capacity building framework. You can consult me on:\n- **Statistical Standards**: CPI, WPI, IIP, NAS, PLFS, and ASI survey methodologies.\n- **Assessment Engineering**: Psychometric MCQ standards, distractor quality, and HITL curation.\n- **Competency Remediation**: Targeted civil services learning pathways on iGOT.\n\nSelect a quick query below or ask any question to begin.`
        : `Welcome to the **MoSPI SmartSkill AI Assistant**, powered by **Google Gemini**.\n\nI provide authoritative civil services guidance on official statistics methodologies, manual ingestion workflows, and iGOT Karmayogi competency training.\n\nSelect an inquiry card below or type your question!`;

      setMessages([
        {
          id: 'welcome-msg',
          sender: 'assistant',
          text: greeting,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          model: 'gemini-3.8-flash',
        }
      ]);
    }
  }, [user]);

  // Scroll to bottom on updates
  useEffect(() => {
    if (isOpen) {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isLoading, isOpen]);

  // Focus input when opened
  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 150);
    }
  }, [isOpen]);

  const handleSendMessage = async (textToSend?: string) => {
    const text = (textToSend || inputMessage).trim();
    if (!text || isLoading) return;

    const userMessageId = `user-${Date.now()}`;
    const newUserMessage: ChatMessage = {
      id: userMessageId,
      sender: 'user',
      text,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages(prev => [...prev, newUserMessage]);
    setInputMessage('');
    setIsLoading(true);

    try {
      const historyTurns: ChatMessageTurn[] = messages
        .filter(m => m.id !== 'welcome-msg' && !m.isError)
        .slice(-6)
        .map(m => ({
          sender: m.sender,
          text: m.text,
        }));

      const res = await api.sendChatMessage({
        message: text,
        history: historyTurns,
        user_name: user?.full_name,
        user_role: user?.role === 'admin' ? 'Admin Trainer' : 'Statistical Officer',
      });

      setActiveModel(res.model || 'gemini-3.8-flash');

      const botMessageId = `assistant-${Date.now()}`;
      const newBotMessage: ChatMessage = {
        id: botMessageId,
        sender: 'assistant',
        text: res.reply,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        model: res.model,
      };

      setMessages(prev => [...prev, newBotMessage]);
    } catch (err: any) {
      const errorMessageId = `error-${Date.now()}`;
      setMessages(prev => [
        ...prev,
        {
          id: errorMessageId,
          sender: 'assistant',
          text: `⚠️ **Notice**: Unable to complete AI generation (${err.message || 'Connection timeout'}). You can retry or reach out to the technical team at **smartskillai3@gmail.com**.`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          isError: true,
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleCopyText = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleClearHistory = () => {
    if (confirm('Clear your current conversation history?')) {
      const welcome: ChatMessage = {
        id: `welcome-${Date.now()}`,
        sender: 'assistant',
        text: `Conversation reset. How else may I assist your statistical workflows or capacity building?`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        model: activeModel,
      };
      setMessages([welcome]);
    }
  };

  // Safe formatting parser for markdown
  const renderFormattedMessage = (content: string) => {
    const lines = content.split('\n');
    const elements: React.ReactNode[] = [];

    lines.forEach((line, idx) => {
      const trimmed = line.trim();

      // Heading 3 / Subheading
      if (trimmed.startsWith('### ')) {
        elements.push(
          <div key={idx} className="mt-3.5 mb-1.5 flex items-center gap-2">
            <span className="w-2 h-2 rounded-sm bg-gradient-to-r from-blue-500 to-indigo-500 shadow-xs shrink-0"></span>
            <h4 className="text-xs sm:text-sm font-bold tracking-tight text-slate-100">
              {formatInlineText(trimmed.replace('### ', ''))}
            </h4>
          </div>
        );
        return;
      }

      // Heading 2 / 1
      if (trimmed.startsWith('## ') || trimmed.startsWith('# ')) {
        elements.push(
          <div key={idx} className="mt-4 mb-2 pb-1 border-b border-white/10">
            <h3 className="text-sm sm:text-base font-extrabold text-white tracking-tight flex items-center gap-2">
              <span className="text-amber-400">§</span>
              {formatInlineText(trimmed.replace(/^#+ /, ''))}
            </h3>
          </div>
        );
        return;
      }

      // Bullet lists
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        elements.push(
          <div key={idx} className="flex items-start gap-2.5 my-1 text-xs sm:text-sm text-slate-200 leading-relaxed pl-1">
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mt-2 shrink-0 shadow-xs shadow-indigo-500/50" />
            <div className="flex-1">{formatInlineText(trimmed.substring(2))}</div>
          </div>
        );
        return;
      }

      // Numbered lists
      const numMatch = trimmed.match(/^(\d+)\.\s+(.*)/);
      if (numMatch) {
        elements.push(
          <div key={idx} className="flex items-start gap-2.5 my-1.5 text-xs sm:text-sm text-slate-200 leading-relaxed pl-1">
            <span className="px-1.5 py-0.2 rounded-md bg-indigo-500/20 text-indigo-300 border border-indigo-400/30 text-[10px] font-bold shrink-0 font-mono mt-0.5">
              {numMatch[1]}
            </span>
            <div className="flex-1">{formatInlineText(numMatch[2])}</div>
          </div>
        );
        return;
      }

      // Empty spacing
      if (!trimmed) {
        elements.push(<div key={idx} className="h-2" />);
        return;
      }

      // Regular paragraph
      elements.push(
        <p key={idx} className="my-1 text-xs sm:text-sm text-slate-200 leading-relaxed">
          {formatInlineText(line)}
        </p>
      );
    });

    return elements;
  };

  const formatInlineText = (text: string): React.ReactNode => {
    const parts = text.split(/(\*\*.*?\*\*|`.*?`)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return (
          <strong key={i} className="font-bold text-white tracking-tight">
            {part.slice(2, -2)}
          </strong>
        );
      }
      if (part.startsWith('`') && part.endsWith('`')) {
        return (
          <code key={i} className="px-1.5 py-0.5 rounded-md bg-white/10 text-cyan-300 font-mono text-[11px] border border-white/15">
            {part.slice(1, -1)}
          </code>
        );
      }
      return part;
    });
  };

  return (
    <>
      {/* 1. ULTRA-SLEEK FLOATING ACTION CAPSULE (Visible when closed) */}
      {!isOpen && (
        <button
          onClick={onOpen}
          className="fixed bottom-6 right-6 z-50 group flex items-center gap-3 px-4 sm:px-5 py-3.5 bg-[#08101E]/95 hover:bg-[#0C182E] text-white rounded-full shadow-[0_12px_40px_-5px_rgba(11,37,69,0.7)] hover:shadow-[0_20px_50px_rgba(99,102,241,0.35)] hover:scale-105 transition-all duration-300 border border-indigo-400/35 backdrop-blur-xl cursor-pointer"
          title="Open MoSPI SmartSkill AI Assistant"
          aria-label="Open AI Assistant"
        >
          {/* Glowing Avatar Orb with Dual Pulse */}
          <div className="relative">
            <div className="w-9 h-9 rounded-full bg-gradient-to-tr from-indigo-600 via-blue-600 to-amber-400 p-[1.5px] shadow-lg">
              <div className="w-full h-full bg-[#08101E] rounded-full flex items-center justify-center group-hover:scale-95 transition-transform">
                <Sparkles className="w-4 h-4 text-amber-300 fill-amber-300/40 group-hover:rotate-12 transition-transform duration-300" />
              </div>
            </div>
            {/* Live Ripple Badge */}
            <span className="absolute -top-0.5 -right-0.5 flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-emerald-400 border-2 border-[#08101E]"></span>
            </span>
          </div>

          <div className="text-left hidden sm:block">
            <div className="flex items-center gap-1.5">
              <span className="text-xs font-black text-white tracking-wide">MoSPI AI Assistant</span>
              <span className="px-1.5 py-0.2 rounded-full text-[9px] font-extrabold bg-gradient-to-r from-amber-400/25 to-amber-300/10 text-amber-300 border border-amber-400/30 uppercase tracking-wider">
                Gemini 3.8
              </span>
            </div>
            <div className="text-[10px] text-slate-300 font-medium tracking-tight">
              Official Statistics Intelligence
            </div>
          </div>
        </button>
      )}

      {/* 2. STATE-OF-THE-ART EXECUTIVE CHAT DOCK (Visible when open) */}
      {isOpen && (
        <div 
          className={`fixed z-50 transition-all duration-300 flex flex-col bg-[#070D18]/95 backdrop-blur-2xl rounded-3xl border border-white/10 overflow-hidden shadow-[0_25px_80px_-15px_rgba(2,10,25,0.85)] ${
            isExpanded 
              ? 'inset-3 sm:inset-6 md:inset-10 max-w-5xl mx-auto' 
              : 'bottom-4 right-4 sm:bottom-6 sm:right-6 w-[95vw] sm:w-[470px] h-[660px] max-h-[88vh]'
          }`}
        >
          {/* AMBIENT TOP LIGHT BEAM */}
          <div className="absolute top-0 left-1/4 right-1/4 h-[1px] bg-gradient-to-r from-transparent via-indigo-400/50 to-transparent pointer-events-none" />

          {/* SLEEK EXECUTIVE HEADER */}
          <div className="relative px-4 py-3.5 sm:px-5 sm:py-4 bg-[#091322]/90 border-b border-white/[0.08] flex items-center justify-between shrink-0">
            <div className="flex items-center gap-3">
              {/* Bot Orb with Radiant Ring */}
              <div className="relative">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-indigo-500 via-blue-600 to-amber-400 p-[1.5px] shadow-md">
                  <div className="w-full h-full bg-[#070D18] rounded-[14px] flex items-center justify-center">
                    <Bot className="w-5 h-5 text-amber-300" />
                  </div>
                </div>
                <span className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-emerald-400 border-2 border-[#070D18] rounded-full"></span>
              </div>

              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-sm sm:text-base font-black tracking-tight text-white">
                    MoSPI SmartSkill AI
                  </h3>
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/15 text-emerald-300 border border-emerald-400/30 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    Online & Grounded
                  </span>
                </div>
                <div className="text-[11px] text-slate-400 flex items-center gap-2 mt-0.5">
                  <span className="font-mono text-cyan-300 text-[10px]">{activeModel}</span>
                  <span className="text-slate-600">•</span>
                  <span className="text-slate-300">iGOT Karmayogi Framework</span>
                </div>
              </div>
            </div>

            {/* Window Action Buttons */}
            <div className="flex items-center gap-1 sm:gap-1.5">
              <button
                onClick={handleClearHistory}
                className="w-8 h-8 rounded-xl bg-white/[0.04] hover:bg-white/[0.1] text-slate-300 hover:text-white border border-white/[0.08] flex items-center justify-center transition cursor-pointer"
                title="Clear Conversation"
              >
                <Trash2 className="w-3.5 h-3.5" />
              </button>

              <button
                onClick={() => setIsExpanded(!isExpanded)}
                className="w-8 h-8 rounded-xl bg-white/[0.04] hover:bg-white/[0.1] text-slate-300 hover:text-white border border-white/[0.08] hidden sm:flex items-center justify-center transition cursor-pointer"
                title={isExpanded ? 'Restore Size' : 'Maximize Workspace'}
              >
                {isExpanded ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
              </button>

              <button
                onClick={onClose}
                className="w-8 h-8 rounded-xl bg-white/[0.04] hover:bg-rose-500/20 text-slate-300 hover:text-rose-200 border border-white/[0.08] hover:border-rose-400/30 flex items-center justify-center transition cursor-pointer"
                title="Close Assistant"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* CHAT MESSAGES SCROLL SURFACE */}
          <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4 bg-gradient-to-b from-[#070D18] via-[#09111F] to-[#070D18]">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex gap-3 ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                {/* Assistant Avatar */}
                {msg.sender === 'assistant' && (
                  <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-[#0B1E38] to-indigo-900 border border-indigo-400/30 text-amber-300 flex items-center justify-center shrink-0 shadow-sm mt-0.5">
                    <Sparkles className="w-4 h-4" />
                  </div>
                )}

                {/* Bubble Container */}
                <div
                  className={`group relative max-w-[88%] sm:max-w-[82%] rounded-2xl p-4 text-xs sm:text-sm shadow-md transition-all ${
                    msg.sender === 'user'
                      ? 'bg-gradient-to-r from-blue-600 via-indigo-600 to-indigo-700 text-white rounded-br-xs border border-indigo-400/30 shadow-indigo-950/40'
                      : msg.isError
                      ? 'bg-rose-950/40 border border-rose-500/40 text-rose-200 rounded-bl-xs'
                      : 'bg-[#0E1A2E]/90 border border-white/[0.08] text-slate-100 rounded-bl-xs shadow-black/40'
                  }`}
                >
                  {/* Bubble Header info */}
                  <div className="flex items-center justify-between gap-4 mb-2 pb-1.5 border-b border-white/[0.06] text-[10px]">
                    <span className={msg.sender === 'user' ? 'text-indigo-200 font-bold' : 'text-slate-400 font-semibold'}>
                      {msg.sender === 'user' ? (user ? user.full_name : 'You') : 'MoSPI AI Intelligence'}
                    </span>
                    <div className="flex items-center gap-2">
                      {msg.model && msg.sender === 'assistant' && (
                        <span className="px-1.5 py-0.2 rounded-md bg-white/[0.06] text-cyan-300 font-mono text-[9px] border border-white/10">
                          {msg.model}
                        </span>
                      )}
                      <span className={msg.sender === 'user' ? 'text-indigo-200/80' : 'text-slate-500'}>
                        {msg.timestamp}
                      </span>
                    </div>
                  </div>

                  {/* Bubble Message Content */}
                  <div>
                    {msg.sender === 'user' ? (
                      <p className="whitespace-pre-wrap leading-relaxed text-white font-medium">{msg.text}</p>
                    ) : (
                      renderFormattedMessage(msg.text)
                    )}
                  </div>

                  {/* Copy Action for Assistant */}
                  {msg.sender === 'assistant' && !msg.isError && (
                    <div className="mt-3 pt-2 border-t border-white/[0.06] flex items-center justify-between text-[11px] text-slate-400">
                      <span className="text-[10px] text-slate-400 font-medium">Authoritative MoSPI Grounding</span>
                      <button
                        onClick={() => handleCopyText(msg.id, msg.text)}
                        className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-white/[0.04] hover:bg-white/[0.1] text-slate-300 hover:text-white border border-white/[0.06] transition text-[10px] cursor-pointer"
                        title="Copy to clipboard"
                      >
                        {copiedId === msg.id ? (
                          <>
                            <Check className="w-3 h-3 text-emerald-400" />
                            <span className="text-emerald-400 font-bold">Copied</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>
                    </div>
                  )}
                </div>

                {/* User Avatar */}
                {msg.sender === 'user' && (
                  <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-slate-800 to-slate-700 text-white flex items-center justify-center shrink-0 shadow-sm mt-0.5 border border-white/15 font-bold text-xs">
                    {user ? user.full_name.charAt(0) : <UserIcon className="w-4 h-4" />}
                  </div>
                )}
              </div>
            ))}

            {/* NEURAL THINKING WAVE */}
            {isLoading && (
              <div className="flex gap-3 items-start">
                <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-[#0B1E38] to-indigo-900 border border-indigo-400/30 text-amber-300 flex items-center justify-center shrink-0 shadow-sm mt-0.5">
                  <Sparkles className="w-4 h-4 animate-spin text-amber-300" />
                </div>
                <div className="bg-[#0E1A2E]/90 border border-indigo-500/30 rounded-2xl rounded-bl-xs p-4 shadow-md max-w-[85%]">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-[10px] font-extrabold uppercase tracking-wider text-cyan-300">
                      Gemini 3.8 Neural Synthesis
                    </span>
                    <span className="px-1.5 py-0.2 rounded-full text-[9px] font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-400/30">
                      MoSPI Methodology
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="flex items-center gap-1.5 py-1">
                      <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" style={{ animationDelay: '0ms' }}></span>
                      <span className="w-2 h-2 rounded-full bg-indigo-400 animate-pulse" style={{ animationDelay: '200ms' }}></span>
                      <span className="w-2 h-2 rounded-full bg-amber-400 animate-pulse" style={{ animationDelay: '400ms' }}></span>
                    </div>
                    <span className="text-xs text-slate-300 font-medium">
                      Consulting official statistics manuals & calculating response...
                    </span>
                  </div>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* STARTER INQUIRY CARDS (Visible when initial chat state) */}
          {messages.length <= 2 && !isLoading && (
            <div className="px-4 py-3 bg-[#0A1322]/95 border-t border-white/[0.08] shrink-0">
              <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider mb-2.5 flex items-center justify-between">
                <span className="flex items-center gap-1.5 text-indigo-300">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                  Suggested Inquiries
                </span>
                <span className="text-[10px] text-slate-400 font-normal">Click any topic to analyze</span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {STARTER_PROMPTS.map((starter, idx) => {
                  const IconComp = starter.icon;
                  return (
                    <button
                      key={idx}
                      onClick={() => handleSendMessage(starter.prompt)}
                      className="text-left p-2.5 rounded-xl bg-white/[0.03] hover:bg-white/[0.08] border border-white/[0.08] hover:border-indigo-400/40 transition-all duration-200 group flex items-start gap-2.5 cursor-pointer shadow-xs"
                    >
                      <div className={`w-7 h-7 rounded-lg bg-gradient-to-br ${starter.color} border flex items-center justify-center shrink-0 mt-0.5 group-hover:scale-110 transition-transform`}>
                        <IconComp className="w-3.5 h-3.5" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="text-xs font-bold text-white group-hover:text-cyan-300 truncate transition-colors">
                          {starter.title}
                        </div>
                        <div className="text-[10px] text-slate-400 truncate mt-0.5 leading-tight">
                          {starter.subtitle}
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* FLOATING INPUT DOCK */}
          <div className="p-3.5 sm:p-4 bg-[#070D18] border-t border-white/[0.08] shrink-0">
            <div className="relative flex items-end gap-2 bg-[#0E1A2E]/90 border border-white/[0.12] focus-within:border-indigo-500 focus-within:ring-2 focus-within:ring-indigo-500/20 rounded-2xl p-2.5 transition shadow-inner">
              <textarea
                ref={inputRef}
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Ask about MoSPI survey methodologies, MCQ psychometrics, or iGOT..."
                className="w-full bg-transparent resize-none outline-hidden text-xs sm:text-sm text-slate-100 placeholder:text-slate-500 max-h-32 min-h-[44px] py-1 px-1.5 leading-relaxed font-normal"
                rows={1}
                disabled={isLoading}
              />

              <button
                onClick={() => handleSendMessage()}
                disabled={!inputMessage.trim() || isLoading}
                className={`p-2.5 rounded-xl flex items-center justify-center transition-all duration-200 shrink-0 shadow-md ${
                  inputMessage.trim() && !isLoading
                    ? 'bg-gradient-to-r from-blue-600 via-indigo-600 to-indigo-700 hover:from-blue-500 hover:to-indigo-600 text-white active:scale-95 shadow-indigo-900/50 cursor-pointer'
                    : 'bg-white/[0.05] text-slate-500 border border-white/[0.05] cursor-not-allowed'
                }`}
                title="Send inquiry"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>

            {/* FOOTER BAR: INFORMATIVE & SLEEK */}
            <div className="flex items-center justify-between mt-2.5 px-1.5 text-[10px] text-slate-400">
              <span className="flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400"></span>
                <span>MoSPI Official Capacity Building • Powered by Gemini 3.8 Flash</span>
              </span>
              <span className="hidden sm:inline text-slate-500">
                Press <kbd className="px-1 py-0.5 rounded bg-white/10 text-slate-300 font-mono text-[9px]">Enter ↵</kbd> to send
              </span>
            </div>
          </div>
        </div>
      )}
    </>
  );
};
